# Generated by Django 3.2 on 2021-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_field',
            field=models.TextField(),
        ),
    ]
