# Generated by Django 3.2 on 2021-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_news_text_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyForToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabinet_five', models.CharField(max_length=250)),
                ('kabinet_four', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
