# Generated by Django 3.2 on 2021-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dutyfortoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyfortoday',
            name='date',
            field=models.DateField(),
        ),
    ]
