# Generated by Django 3.2 on 2021-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificatestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(blank=True, null=True)),
                ('numberkey', models.TextField(blank=True, db_column='numberKey', null=True)),
                ('beforedate', models.DateField(blank=True, db_column='beforeDate', null=True)),
                ('afterdate', models.DateField(blank=True, db_column='afterDate', null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CertificateStore',
                'managed': False,
            },
        ),
    ]
