# Generated by Django 3.2 on 2021-05-14 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORGANIZATION',
            fields=[
                ('INN', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('NAME', models.CharField(max_length=250)),
                ('DOC_RESP_PERSON', models.FileField(blank=True, upload_to='ORG/')),
            ],
        ),
        migrations.CreateModel(
            name='ROLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WORKER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('DOC_AGREEMENT', models.FileField(blank=True, upload_to='WORKERS/')),
                ('ADDITIONAL_INFO', models.TextField(blank=True)),
                ('RESP_PERSONE', models.BooleanField(default=False)),
                ('ORG_INN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elbudget.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EbRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='client2org', to='elbudget.worker')),
                ('RESP_PERSONE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='respperson2org', to='elbudget.worker')),
                ('REQUEST_TYPE', models.CharField(choices=[('Предоставление доступа', 'Предоставление доступа'), ('Добавление полномочий', 'Добавление полномочий'), ('Прекращение доступа', 'Прекращение доступа'), ('Смена сертификата', 'Смена сертификата')], default='Предоставление доступа', max_length=25)),
                ('GETTING_TIME', models.DateField(default=datetime.date(2021, 5, 14))),
                ('NUMBER', models.CharField(blank=True, max_length=25, null=True)),
                ('EXECUTOR', models.CharField(blank=True, max_length=100, null=True)),
                ('RESULT', models.CharField(choices=[('Исполнено', 'Исполнено'), ('Отказано', 'Отказано'), ('В процессе', 'В процессе')], default='Исполнено', max_length=25)),
                ('COMMENT', models.TextField(blank=True, null=True)),
                ('MESSAGE_NUMBER', models.CharField(blank=True, max_length=25, null=True)),
                ('MESSAGE_DATA', models.DateField(blank=True, null=True)),
                ('TRACK_NUMBER', models.CharField(blank=True, max_length=50)),
                ('IsDEBTOR', models.BooleanField(default=False)),
                ('ADDED_ROLES', models.ManyToManyField(blank=True, to='elbudget.ROLE')),
                ('ORG_INN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elbudget.organization')),
            ],
        ),
    ]
