# Generated by Django 3.2.2 on 2021-05-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.TextField()),
                ('DOC_AGREEMENT', models.FileField(upload_to='CLIENTS/')),
                ('RESP_PERSONE', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION',
            fields=[
                ('INN', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('NAME', models.TextField()),
                ('<django.db.models.fields.TextField>', models.FileField(upload_to='ORG/')),
            ],
        ),
        migrations.CreateModel(
            name='EbRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REQUEST_TYPE', models.CharField(choices=[('new', 'Предоставление доступа'), ('add', 'Добавление полномочий'), ('stp', 'Прекращение доступа'), ('chg', 'Смена сертификата')], default='new', max_length=3)),
                ('GETTING_TIME', models.DateField(db_column='GETTING_TIME')),
                ('NUMBER', models.TextField(blank=True, null=True)),
                ('EXECUTOR', models.TextField(blank=True, null=True)),
                ('RESULT', models.CharField(choices=[('acc', 'Исполнено'), ('rej', 'Отказано'), ('pro', 'В процессе')], default='pro', max_length=3)),
                ('COMMENT', models.TextField(blank=True, null=True)),
                ('MESSAGE_NUMBER', models.TextField(blank=True, null=True)),
                ('MESSAGE_DATA', models.TextField(blank=True, null=True)),
                ('TRACK_NUMBER', models.TextField(blank=True, null=True)),
                ('CLIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client2org', to='elbudget.client')),
                ('ORG_INN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elbudget.organization')),
                ('RESP_PERSONE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respperson2org', to='elbudget.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='ORG_INN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elbudget.organization'),
        ),
    ]
