# Generated by Django 3.2 on 2021-05-17 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='GETTING_TIME',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
    ]
