# Generated by Django 3.2.3 on 2021-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='TRACK_NUMBER',
            field=models.TextField(blank=True),
        ),
    ]
