# Generated by Django 3.2.2 on 2021-05-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='CLIENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='client2org', to='elbudget.client'),
        ),
        migrations.AlterField(
            model_name='ebrequest',
            name='RESP_PERSONE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='respperson2org', to='elbudget.client'),
        ),
    ]
