# Generated by Django 3.2.2 on 2021-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0002_auto_20210512_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='MESSAGE_DATA',
            field=models.DateField(db_column='MESSAGE_DATA'),
        ),
    ]
