# Generated by Django 3.2 on 2021-05-18 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0002_alter_ebrequest_getting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='GETTING_TIME',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
    ]
