# Generated by Django 3.2.2 on 2021-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0003_alter_ebrequest_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='REQUEST_TYPE',
            field=models.CharField(choices=[('Предоставление доступа', 'Предоставление доступа'), ('Добавление полномочий', 'Добавление полномочий'), ('Прекращение доступа', 'Прекращение доступа'), ('Смена сертификата', 'Смена сертификата')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='ebrequest',
            name='RESULT',
            field=models.CharField(choices=[('Исполнено', 'Исполнено'), ('Отказано', 'Отказано'), ('В процессе', 'В процессе')], default='pro', max_length=25),
        ),
    ]
