# Generated by Django 3.2.3 on 2021-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbudget', '0003_alter_ebrequest_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrequest',
            name='EXECUTOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebrequest',
            name='MESSAGE_NUMBER',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ebrequest',
            name='NUMBER',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ebrequest',
            name='TRACK_NUMBER',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='INN',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='NAME',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='worker',
            name='FIO',
            field=models.CharField(max_length=100),
        ),
    ]
